services:
  #our PostgreSQL database
  db:
    # The docker image of postgres
    image: postgres:latest
    # ports to expose to the host container
    # 5432 is the default PostgreSQL ports
    ports:
      - "5432:5432"
    # if we accidentally kill the running container,
    # Docker compose will restart it
    restart: always
    # The PostgreSQL DOcker container uses enviroment variables to
    # read configuration, here we set the password
    # DO NOT store plaintext passwords in source control.
    # We do so here as this is a builder
    environment:
      POSTGRES_PASSWORD: changemeinprod!